project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercise
        menu: 
          - text: Hands-on Exercise 1
            href: Hands-on_Ex_1/Hands-on_Ex_1.qmd
          - text: Hands-on Exercise 2.1
            href: Hands-on_Ex_2/Hands-on_Ex_2.qmd
          - text: Hands-on Exercise 2.2
            href: Hands-on_Ex_2/Hands-on_Ex_2a.qmd
          - text: Hands-on Exercise 2.3
            href: Hands-on_Ex_2/Hands-on_Ex_2b.qmd
          - text: Hands-on Exercise 3
            href: Hands-on_Ex_3/Hands-on_Ex_3.qmd
      - text: In-class Exercise
        menu: 
          - text: In-class Exercise 1
            href: In-Class_Ex_1/In-Class_Ex_1.qmd
          - text: In-class Exercise 2
            href: In-Class_Ex_2/In-Class_Ex_2.qmd
          - text: In-class Exercise 3
            href: In-Class_Ex_3/In-Class_Ex_3.qmd
          - text: In-class Exercise 4
            href: In-Class_Ex_4/In-Class_Ex_4.qmd
          - text: In-class Exercise 5
            href: In-Class_Ex_5/In-Class_Ex_5.qmd
      - text: Take-Home Exercise
        menu: 
          - text: Take-Home Exercise 1
            href: Take-Home_Ex_1/Take-Home_Ex_1.qmd
          - text: Take-Home Exercise 2
            href: Take-Home_Ex_2/Take-Home_Ex_2.qmd
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

